# Generated by Django 3.0.2 on 2020-01-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='image',
            field=models.ImageField(default='no pic', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='song_genre',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Movie', 'Movie'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Alternative/Indie', 'Alternative/Indie'), ('Remix', 'Remix'), ('Instrumental', 'Instrumental'), ('Folk', 'Folk'), ('Electronic', 'Electronic')], default='Unknown', max_length=200),
        ),
    ]
